version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - ./db_data:/data/db
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongorootpassword
      MONGO_INITDB_DATABASE: CompanyDB 
  
  mongodb-UI:
    image: mongo-express:1-18-alpine3.18
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoroot
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongorootpassword
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpassword
      ME_CONFIG_MONGODB_URL: mongodb://mongoroot:mongorootpassword@mongodb:27017/